### ISSUE TITLE
Machine page has wrong images on mobile. 

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#14]
Not sure why, but images change on mobile. Seems like useless data which is loaded.

**Comment by leo** [comment]
What exactly do you mean? Which images are wrong? Screenshot? :P

**Comment by davehakkens** [comment]
Desktop: 
![image](https://cloud.githubusercontent.com/assets/13672737/13906759/ceec72f4-eede-11e5-9ed6-4ded66d3e3dd.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/13672737/13906761/dfdf4460-eede-11e5-9760-6e64a030799e.png)

(also the header images change)
