### ISSUE TITLE
BG Video Plan Page

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#15]
Header image should be a background video like Phonebloks and Story hopper. We think "play the video" button shouldn’t open the full video in another page. Is there another way to make something out of this?
If not,  link it to the campaign page.

**Comment by thisismattia** [comment]
What's your opinion here @leo ?

The original concept was to have the video playing in the bg by default with a thick white overlay. 
Like is happening here:

http://fantasy.co/

As users click "play video" the text and overlay would disappear leaving space for the video to be watched.
Is this even technically possible?

**Comment by leo** [comment]
@davehakkens is currently creating a video that will be added behind that white overlay.
