### ISSUE TITLE
Fix load more news

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#16]
Load more news button doesn't work. If it is difficult to make this with RSS we could also load +/-10 items and make a button underneath "watch all news" which redirects you to http://davehakkens.nl/#preciousplastic

**Comment by leo** [comment]
It IS possible, but much more difficult. I also think that it's a good idea to forward users to your site if they want to read more since they can also subscribe to your RSS feed there. Otherwise, they might not even find it. The "news" page now also shows 10 items! :blush:
