### ISSUE TITLE
Side Bar Menu

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#17]
I would say for the side bar menu we should refer to slack for reference.
https://get.slack.help/hc/en-us/categories/200111606-Using-Slack
They've done it beautifully.

What it needs is:
- [x] Stack to top left (position: fixed?)
- [x] Hover state using our border grey

**Comment by leo** [comment]
Instead of the "border grey", I've used a slightly darker color. Let me know if you don't like it!

**Comment by thisismattia** [comment]
hey leo..is it possible to get the side bar element container to highlight instead of the text itself as it is happening on slack website?
Or is it too much of a workaround?

**Comment by leo** [comment]
@mattia-io What do you mean with "highlight"?

**Comment by leo** [comment]
Fixed in afd92ae4dcd1b2a4ad22e943d4414aff3a6897d2

**Comment by thisismattia** [comment]
![screen shot 2016-03-21 at 14 20 41](https://cloud.githubusercontent.com/assets/17761877/13919883/57c6dbfa-ef70-11e5-94d7-f6671390333b.png)

**Comment by thisismattia** [comment]
Fixed looks really good now...any chance we can make it not overlap the footer?

![screen shot 2016-03-21 at 14 22 52](https://cloud.githubusercontent.com/assets/17761877/13919919/8070d178-ef70-11e5-8de9-a02696e3e9b3.png)

**Comment by leo** [comment]
Already working on the footer thing. Regarding highlighting different sections: That basically means that all pages would be on a single one (which is pretty big). The sections on Slack's page only contain a few bullet points (not like our site). So I spoke to @davehakkens in the beginning and we made the decision to keep it like that.

**Comment by leo** [comment]
Fixed the footer problem in f7bf44cc563c3c9d8aea04aebb3a39fe2cc9fff9
