### ISSUE TITLE
Share box

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#19]
One little nifty thing. 
Possible to add some Ease-In behaviour to the sliding panel?
Currently sliding feels a bit dull.

**Comment by leo** [comment]
What do you mean with "sliding panel"? :blush:

**Comment by thisismattia** [comment]
Ah sorry..I mean the sliding sharing box..when user click SPREAD

**Comment by leo** [comment]
Now it uses [this](http://easings.net/#easeInOutCubic) function. If you don't like it, please choose a different one from [here](http://easings.net/).
