### ISSUE TITLE
Hmenu

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#36]
Main Hmenu does not switch to X icon as it is pressed..
![screen shot 2016-03-22 at 12 26 50](https://cloud.githubusercontent.com/assets/17761877/13950144/8d39e98a-f029-11e5-8f22-71bbdc515ac1.png)

**Comment by leo** [comment]
While this isn't something that's actually necessary to get implement, I've did it! :wink:

**Comment by leo** [comment]
Done in 5043ff80a6b3c844e303c66f1a81f920f48d3b21
