### ISSUE TITLE
Submenu mobile overlay issues

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#37]
I think the z-index is a bit messed up on mobile for the submenu..the video is overlapping at times

![screen shot 2016-03-22 at 12 31 16](https://cloud.githubusercontent.com/assets/17761877/13950432/39c83494-f02b-11e5-84fe-60ee2000b174.png)
![screen shot 2016-03-22 at 12 31 25](https://cloud.githubusercontent.com/assets/17761877/13950433/39c9bfc6-f02b-11e5-8a04-736ed5a5442b.png)
![screen shot 2016-03-22 at 12 31 33](https://cloud.githubusercontent.com/assets/17761877/13950434/39cc4cd2-f02b-11e5-8c11-5affb026f841.png)

**Comment by leo** [comment]
@mattia-io Not able to reproduce this. Works completely fine for me. The menu shouldn't overlay the video at all, it should rather push it down:

<img width="503" alt="screen shot 2016-03-22 at 13 22 46" src="https://cloud.githubusercontent.com/assets/6170607/13951430/2f9fa15e-f031-11e5-92ee-11d3557945f5.png">

What device are you testing on? Does reloading fix the issue?

**Comment by leo** [comment]
> Does reloading fix the issue?

Yes, it does! :blush:
