### ISSUE TITLE
Sharing bottom bar

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#38]
Could we have the entire yellow bottom bar clickable?
This would ease user interaction making more people share (hopefully)

![screen shot 2016-03-21 at 22 52 02](https://cloud.githubusercontent.com/assets/17761877/13950548/f23395b4-f02b-11e5-9e1b-85281a01c31a.png)

**Comment by leo** [comment]
We can do that! However, it will take away our ability to add a "Close" button later.

**Comment by leo** [comment]
@leo Nah, we can also make it thinner!
