### ISSUE TITLE
Bug in extra

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#39]
items on the extra page are often stacked on top of each other...

![image](https://cloud.githubusercontent.com/assets/13672737/13964054/43a25f5c-f068-11e5-841b-71d6d47c1f2b.png)

**Comment by leo** [comment]
And again, wrong class name :blush:

<img width="263" alt="screen shot 2016-03-22 at 21 03 41" src="https://cloud.githubusercontent.com/assets/6170607/13966230/b4d427a6-f071-11e5-9c51-2d6907c48fa0.png">
