### ISSUE TITLE
Inline text link

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#44]
What is our color policy in regards..right now we have default blue and purple that looks terrible..
Dave, shall we use the primary green? Or the red (more visible)?

![screen shot 2016-03-23 at 12 49 03](https://cloud.githubusercontent.com/assets/17761877/13985253/f492415e-f0fb-11e5-8ddf-1ba95789bdfe.png)
![screen shot 2016-03-23 at 12 54 55](https://cloud.githubusercontent.com/assets/17761877/13985254/f4962f9e-f0fb-11e5-859c-434b8a02c378.png)

**Comment by leo** [comment]
My suggestion is to make it match the color of the current section (in this case green) - like the button.

**Comment by thisismattia** [comment]
Agreed. @davehakkens ?

**Comment by davehakkens** [comment]
i'm up for that! Does it work with the yellow?
Otherwise a nicer blue works for me as well. #79BAD9
