### ISSUE TITLE
Logo Replacement

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#47]
Dave let's make sure we replace the correct version of the logo all across the website

This is the latest version that I have on my laptop..same s you?

[PP_Logo.zip](https://github.com/hakkens/precious-plastic/files/185980/PP_Logo.zip)

**Comment by davehakkens** [comment]
I've added the logo in the download-pack: https://github.com/hakkens/precious-plastic-kit
Replaced it on the website with the final version
