### ISSUE TITLE
Sharing Count

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#50]
Sharing count does look like is wired up or working..can anyone check on that?

**Comment by leo** [comment]
Are you asking if it's working? It is! :blush:

**Comment by thisismattia** [comment]
Mmmh...but it shows zero shares at my end and I know that at least I have shared it once :)

![screen shot 2016-03-24 at 18 57 32](https://cloud.githubusercontent.com/assets/17761877/14026254/515c9514-f1f2-11e5-8ea4-6506b4a7bcb5.png)

**Comment by leo** [comment]
@mattia-io Can you share the output of your [browser console](https://developer.chrome.com/devtools/docs/console)?

**Comment by thisismattia** [comment]
Of course

![screen shot 2016-03-24 at 20 40 52](https://cloud.githubusercontent.com/assets/17761877/14029146/bd56d7f8-f200-11e5-9ff8-89c2cfac6e90.png)

**Comment by leo** [comment]
@mattia-io Works fine for me. After doing some research, it looks like one of your Extensions is causing this problem. Read more [here](https://bugs.chromium.org/p/chromium/issues/detail?id=360583). Try disabling all of them and try it again! :blush:

**Comment by thisismattia** [comment]
Interesting...indeed it is working on different browser!
