### ISSUE TITLE
START button

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#52]
Sorry guys to bring this up again..but our most important button across the website is often invisible on our mainpage and difficult to spot on other pages too..

We need to find a better solution- @davehakkens ?

Full green/ white text with darker green on hover?
Or just inverted from current?

![screen shot 2016-03-24 at 19 21 44](https://cloud.githubusercontent.com/assets/17761877/14027031/f7a21388-f1f5-11e5-9dc1-962d01a9a133.png)

**Comment by leo** [comment]
A lighter green, if you ask me!

**Comment by davehakkens** [comment]
honestly i’m quite ok with it. Quite visible on other pages.  
However open for other suggestions, let me know what you think is the best

Op donderdag 24 maart 2016, om 20:18 heeft Mattia het volgende geschreven:

**Comment by leo** [comment]
Using the text color or something similar might also be a great idea (so that it's only green on the "Start" pages):

<img width="653" alt="screen shot 2016-03-25 at 11 25 00" src="https://cloud.githubusercontent.com/assets/6170607/14042649/40f040e2-f27c-11e5-963b-1ddf2f8d69ae.png">

**Comment by thisismattia** [comment]
Like this option..ATM we have 3 different colors for that button..
I would keep it consistent in CAMPAIGN, PLAN, MACHINE, CREATIONS, NEWS and change it for START

**Comment by leo** [comment]
@mattia-io Yep, exactly like that! Are you okay with that, @davehakkens? Or do you have a different idea?

**Comment by davehakkens** [comment]
Not sure if I fully understand it... But if you guys are up for it i'm in as well!
