### ISSUE TITLE
Thanks to dumpark

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#54]
Hey..we need to include a big up for the guys at dumpark in the thanks page. 
They jumped in right away and did a great job !!
@davehakkens?

**Comment by davehakkens** [comment]
hmm.. not sure if that is fair against you guys. I mean its nice what they did. But you are all involved much more. But i'll defenitly make a tweet/post about it when its running stable!

**Comment by thisismattia** [comment]
I am easy

**Comment by leo** [comment]
Fixed in 3292822c350910e048b58cafdf26405fda45e951
