### ISSUE TITLE
Weird signs on ~analitics~?

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#55]
![image](https://cloud.githubusercontent.com/assets/13672737/14124924/9bd8b20c-f608-11e5-9320-59c187a3f379.png)

**Comment by leo** [comment]
This is intended. See Slack for more details.

**Comment by thisismattia** [comment]
I think it stands for Circa or Ca...

**Comment by leo** [comment]
@davehakkens @mattia-io Exactly. It's called a "tilde" and in math, two of them one above the other usually stand for "approximately equal to". But they're also being used as single ones to indicate that a certain amount has been calculated approximately.

![tumblr_inline_mp9kum0he91qz4rgp](https://cloud.githubusercontent.com/assets/6170607/14125424/6b423386-f60b-11e5-9c3e-7b96a0af4248.png)

**Comment by davehakkens** [comment]
I know the character. But is this because we want it or because we haven't got another option? If it's the first i'd say a specific number is much more interesting..

**Comment by leo** [comment]
@davehakkens Please take a look at Slack, as I said. This is only a temporary solution. :blush:

**Comment by davehakkens** [comment]
Sorry, couldn't find it! But ok :+1:
