### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#56]
Hello,

Testing on a friend android I encountered some issues..attachements below

![12966178_10156776524445301_397161639_n](https://cloud.githubusercontent.com/assets/17761877/14276792/804057da-fb20-11e5-9630-07990b339185.jpg)
![12966191_10156776523970301_1024861291_n](https://cloud.githubusercontent.com/assets/17761877/14276793/804292ac-fb20-11e5-820a-167071aebc26.jpg)
![12966452_10156776524315301_11396734_n](https://cloud.githubusercontent.com/assets/17761877/14276794/8043cc1c-fb20-11e5-861e-72e083438972.jpg)

**Comment by thisismattia** [comment]
Data in the analytics are buggy and as you click spread it send you back top page

**Comment by leo** [comment]
@mattia-io You you attach the Android version? And are you able to update in the system's settings, or is it a fixed version for your device?

**Comment by thisismattia** [comment]
That is the android version.
Is not my phone. Was just testing from other devices to get a broad range of devices

**Comment by leo** [comment]
@mattia-io No, I'm talking about the actual version of the operating system you're using (`2.0.0` for example) - as devs say it: "The version tag".

**Comment by leo** [comment]
Closing this on behalf of @mattia-io, since we're not able to retrieve the version tag to test on that certain version. Current version of Android seems to work fine.
