### ISSUE TITLE
User's flagged

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#57]
1. http://preciousplastic.com/contact/videos/support is broken
2. Looking for a RSS feed or such from your page, to connect to my
   Liferea and to https://libtech.website

@dave any opinion on possibly implementing RSS feeds?

**Comment by leo** [comment]
I don't remember that "http://preciousplastic.com/contact/videos/support" ever existed? 😄 As far as I know, only [this](http://preciousplastic.com/contact) page exists under this path. More details?

**Comment by thisismattia** [comment]
Let's wait for dave. I think it should redirect to the support page on the videotutorial section.

**Comment by davehakkens** [comment]
Can’t remember that link either.  
i’d say you are referring the the url Leo is talking about..
http://preciousplastic.com/videos/support/
or this one
http://preciousplastic.com/contact/

Op dinsdag 12 april 2016, om 16:35 heeft Mattia het volgende geschreven:

**Comment by leo** [comment]
Closing this now, since the upper URLs seem to work fine. Please re-open if there's anything else we need to fix here.
