### ISSUE TITLE
Enable translations

### ISSUE THREAD

**Issue by shakaran** [leo/plastic#59]
I would like translate your fully website to Spanish for free. It is only needed that you add l18n support in your ruby project, Would be possible?

http://guides.rubyonrails.org/i18n.html

I know Ruby & Rails too in case that you want help too.

**Comment by leo** [comment]
@shakaran Thank you for your suggestion! But in the current state of the site, it's not possible to add translations using Ruby or Jekyll plugins. The reason for this is that we're hosting it on Github Pages.

But making it available under a different path ("/language/..") might be possible.

@davehakkens ^

**Comment by shakaran** [comment]
@leo Thanks Leo! Well I can translate the fully site in a couple of hours, it doesn't have a lot text, so if you can put the site hosted in another place could be easily. 

I suggest you a cheap and small Digital Ocean droplet, in case that you consider that option, if you want use my referal link you will get $10 for free https://m.do.co/c/46d666cd2390

Just let me know when you enable the translations and I quickly translate all the strings. For me it is important get a nice enviroment free of plastic and keep the nature clean :)

**Comment by thisismattia** [comment]
@leo @davehakkens we're currently receiving tons of emails from people that want to offer help translating the website or video. 
Would be phenomenal to find a way to enable this crowdsourced input- as it represents a unique opportunity to achieve one of our main goal, reaching as many people as possible.

**Comment by thisismattia** [comment]
Guyz!

Someone at OSCE pointed me to this website as a great tool for translation- maybe it could be useful I don't know. I leave it up to @leo to say if is an option for us or not
https://www.transifex.com/

They also have an opensource page
https://www.transifex.com/customers/open-source/

**Comment by leo** [comment]
We're working on https://github.com/hakkens/precious-plastic/pull/63
