### ISSUE TITLE
Links not styled

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#61]
Hey @leo @davehakkens 

Links in the machine page are unstyled. Can we get them either red or lightblue like in the plan page.
I did try to push a commit but I don't think it worked for some reasons :(

![screen shot 2016-04-17 at 14 27 39](https://cloud.githubusercontent.com/assets/17761877/14587045/3b96f4d8-04ab-11e6-9f21-4c77f755fe42.png)

**Comment by leo** [comment]
Just a quick tutorial: You don't need to mention Dave or me when opening an issue like this. Since we're both contributors of this repository, we'll receive notifications anyway.
