### ISSUE TITLE
Video isn't working on Internet Explorer

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#62]
We got quite a few mail about people not being able to see the videos on our website. 
Not sure what's the problem, so i'll try to gather more feedback.
Is there a way to fix it or show a link incase the video doesn't work?

Detail from people where it didn't work so far
Susan: My Browser is Internet Explorer; Dell XPS, Windows 7

**Comment by leo** [comment]
Hmm, that's really weird. I mean, can you ask them if they're able to view **embedded** YouTube videos on other sites? Because as far as we're concerned, there's probably not much we can do about it (YouTube handles that stuff)... 🙈 

Screenshots of the browser window and/or the console would be very helpful as well!

**Comment by davehakkens** [comment]
Yes, they are able to view other embeds and videos from Youtube itself. –Hard to ask some old lady for a screenshot from the console. But i’ll try!

Op dinsdag 19 april 2016, om 14:03 heeft Leonard Lamprecht het volgende geschreven:

**Comment by davehakkens** [comment]
another one where it doesn't work.  Internet Explorer version 11
![unnamed](https://cloud.githubusercontent.com/assets/13672737/15170290/283d2db6-1762-11e6-8aca-d7a42f3e01c3.jpg)

**Comment by leo** [comment]
@davehakkens I honestly don't remember that it was possible to click on the difficulty. As far as we've implemented it, you can only click on the time...

**Comment by davehakkens** [comment]
I think he just didn't t understood those chapters because nothing happened. Probably because there wasn't a video showing..
