### ISSUE TITLE
Start translating?

### ISSUE THREAD

**Issue by gperdomo** [leo/plastic#68]
Hi.

I am able to translate the pages into Spanish by adding branches to each page with the text translated. However, I don't know if I should do that now, considering changes being made to make the site more easily translatable. Please let me know if I should wait.

Cheers,
Giselle

**Comment by leo** [comment]
We're currently working on a guide on how to add new translations. I will let you know when it's ready!

**Comment by pmargreff** [comment]
Hi guys, I can help with portuguese (Brazil), the pages and maybe the project documentation too.

**Comment by sylvainv** [comment]
@leo that's very nice, but you could have dropped a line in https://davehakkens.nl/community/forums/topic/translating-our-content/ to say you are working on that. I mentioned I was working on making the website translatable. That would have saved me 2 days of actually doing the same work you are doing. My bad too, should have created an issue too.

**Comment by leo** [comment]
@sylvainv Oh, didn't notice that post! I'm sorry. I'm not really active on Dave's forum...

**Comment by cironis-adam** [comment]
Hey guys,
could you let me know what's the status of the guide on how to translate? 
We want to translate the website to Czech but I don't think translating the HTML files is the right way to do it. It's not easy for general public and makes it uneasy for future code changes. I found a [Jekyll plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin) which would implement variables and then phrases would be in simple text file for each language. I met with @DanielSuska and we can make it work. What do you think about that?
