### ISSUE TITLE
A few language issues and thanks!

### ISSUE THREAD

**Issue by davehakkens** [leo/plastic#72]
First of @GjjvdBurg AWESOME what you have done so far for the translation. This was something we really wanted to get going but didn't have the manpower for it. Big thanks 💪
Also thanks @leo for helping to implement it! Really starting to love this whole Github-vibe

I've followed most of your developments, but I might have missed a few. Got 2 issues..
1: Where to select the language?
2: Links are shown double in the "start" section, seems like you can click the german and english one. Perhaps remove german language until fixed?
<img width="327" alt="schermafbeelding 2016-04-29 om 14 04 44" src="https://cloud.githubusercontent.com/assets/13672737/14911771/36a375a0-0e15-11e6-94b8-f03ae177d77f.png">

Let me know when everything is in place and we can invite people to translate! :)

**Comment by leo** [comment]
Disabled them temporarily. We'll have to set um a guide for telling people how to translate the site, before we invite someone... :blush:

**Comment by GjjvdBurg** [comment]
@davehakkens @leo No problem, glad I can help out in a small way with this great project! The second issue should be fixed with #73. I haven't implemented a language selector because I didn't know if you guys wanted to decide on how to do this by yourselves. I'm definitely willing to help with this if you like though.

**Comment by leo** [comment]
@GjjvdBurg Thanks for fixing the issue. I just re-enabled the german translation and everything seems to work fine!

@davehakkens Can you add the language selector design to the sketch file in the future? I'm going to open a special issue for this (https://github.com/hakkens/precious-plastic/issues/75).
