### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by leo** [leo/plastic#75]
A dropdown that lets you switch between translations of the site.

**Comment by sylvainv** [comment]
@leo I am curious as to why you didn't choose to use i18n strings for the translation ? With a website per language, the more language there is, the more html there will be. I made a version using i18n strings if you are interested. So there are multiple translation but only one html

**Comment by leo** [comment]
@sylvainv I didn't create this update (as you can see in the commit stream). If you want, you can show us your version as well... :blush:

**Comment by sylvainv** [comment]
@leo I uploaded a version on my fork: https://github.com/sylvainv/precious-plastic/tree/feature/translation

The default translation for it is french, so it will load french at first. Other language selectors are on the bottom. Translation files are in `_data`. I only translated the home page in French. But you'll get the idea.

**Comment by leo** [comment]
@sylvainv I cannot find `_data`. Where exactly is it located? 😊

**Comment by sylvainv** [comment]
@leo you should be able to see it now.

**Comment by leo** [comment]
@sylvainv Ahhh, now I get it! :blush: Sadly, I think this won't work for us. Mostly because we've decided to host our site on GitHub Pages for convenience (like mentioned in `README.md`). And since GitHub Pages doesn't support any others than [these](https://pages.github.com/versions/) plugins, there's no other way to do this...

As an example, they don't support "jekyll-language-plugin".

**Comment by davehakkens** [comment]
Sorry for being slow on this. Guess this is the only thing left to get translation on the website right?
Honestly i'\m not sure what kind of selector to choose. Think it should be simple and basis. 
Something like below? I'm also ok if you guys make something, you have a better understanding of what is easy to add.. 

![image](https://cloud.githubusercontent.com/assets/13672737/15170908/c83fecf4-1767-11e6-8e68-14323e5682cc.png)

![image](https://cloud.githubusercontent.com/assets/13672737/15170920/ee7c1a0a-1767-11e6-89ee-3edd621e1b32.png)

**Comment by leo** [comment]
@davehakkens Yep, why not! However, I think the icons should be flat and the language selector somewhere within our container (not outside).

**Comment by davehakkens** [comment]
Sorry this been on hold for so lang. Others things keep coming at my plate. 
Whats the best way to proceed?  I'm ok if its inside the container, or footer if we need more space.
Lets finish this small tiny little step,  so we can get the excited translators going!

**Comment by leo** [comment]
@davehakkens They're already able to contribute. But regarding the language selector, we'll need a polished design... :blush: I'd say at least put it into the footer and use some better flag icons.

**Comment by davehakkens** [comment]
Ad, didn’t know that!  
Is there a standard template/flag set we use? Or make something custom in sketch?

Op zondag 5 juni 2016, om 21:56 heeft Leo Lamprecht het volgende geschreven:

**Comment by leo** [comment]
@davehakkens If you're able to make something custom in sketch/illustrator, that would probably be the cleanest way to do it! But if not, you can looks for a flat pack on [Icon Finder](https://www.iconfinder.com). The flags on your picture above seem like they aren't really flat (they're beveled).

**Comment by davehakkens** [comment]
yes, those flags are a very rough picked example somewhere from google. Let me make something in Sketch.

Op zondag 5 juni 2016, om 22:00 heeft Leo Lamprecht het volgende geschreven:

**Comment by davehakkens** [comment]
OK. made something in Sketch, in the footer of the website. A little button you can click with a dropdown to select another language. Attached you can find the information:
- a screenshot of the clicked, and non-clicked version desktop. 
- a screenshot of the clicked, and non-clicked version mobile.
- Sketch file.
- A .zip with all flag icons. Not sure if you need it but who knows.

Hope that does the job. Let me know if you need anything else, or have other suggestions.

![image](https://cloud.githubusercontent.com/assets/13672737/15806340/df9b2538-2b73-11e6-98f1-ad6a58dc4b35.png)
![image](https://cloud.githubusercontent.com/assets/13672737/15806351/fea2033e-2b73-11e6-9bba-7b7c921c44d6.png)

[language.zip](https://github.com/hakkens/precious-plastic/files/299387/language.zip)

[flags_2.zip](https://github.com/hakkens/precious-plastic/files/299386/flags_2.zip)
