### ISSUE TITLE
Menu bar not visible when I have it at half my screen

### ISSUE THREAD

**Issue by Jerzeek** [leo/plastic#90]
![image](https://user-images.githubusercontent.com/22919620/87025105-40a7ee00-c1da-11ea-87c3-c23a348df646.png)

I can click where the hamburger menu should be but it's not visible
Windows 10
Chrome 83
15inch 1920x1080 screen

It happens when the screen is smaller than 1000px

✌

**Comment by thisismattia** [comment]
Thanks @Jerzeek let me have a look 💪
