### ISSUE TITLE
Navbar is not working

### ISSUE THREAD

**Issue by thisismattia** [leo/plastic#92]
Issue: navbar on [preciousplastic.com](http://preciousplastic.com/) stopped working

The website is built on webflow. 
On webflow staging website works nice and smooth. 
Also once I download and test locally on my machine works good. 
The moment I upload the code to github and push it live it does not work any more. (or actually it has been behaving SUPER weird where it works for an hour or two then goes back not workin :scream:)

I have tried to rebuild parts of the component first, then the entire navbar component, eventually i even duplicated the site to see if there was any underlying issues or something. Nothing worked so far. I am now thinking it has to do with JS not loading properly on github for some reasons?

**Comment by pReya** [comment]
I've noticed the same thing. For me (using MacOS and Firefox) it works when I disable Firefox's "Enhanced Tracking Protection" (the Shield icon in the address bar). However, by default, it will not work.
